name: Auto Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    
    # Build the project
    - name: Build HsMod
      run: dotnet build --configuration Release --no-restore
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    # Push to Telegram
    - name: Post to Telegram
      shell: pwsh
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
        COMMIT_MESSAGE: |
          New push to GitHub
          ```
          ${{ github.event.head_commit.message }}
          ```
          by `${{ github.event.head_commit.author.name }}`
          See commit detail [here](${{ github.event.head_commit.url }})
      run: |
        $escaped = & python -c "import os, json; print(json.dumps(os.environ['COMMIT_MESSAGE']))"
        $mediaJson = @"
        [{"type":"document","media":"attach://canary","parse_mode":"MarkdownV2","caption":$escaped}]
        "@
        $url = "https://api.telegram.org/bot$env:BOT_TOKEN/sendMediaGroup"
        & curl.exe -v $url `
          -F "chat_id=$env:CHAT_ID" `
          -F "message_thread_id=$env:MESSAGE_THREAD_ID" `
          -F "media=$mediaJson" `
          -F "canary=@./HsMod/Release/HsMod.dll"
