name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
    - bepinex5
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
   
    - name: Restore dependencies
      if: steps.check-updates.outputs.has_updates == 'true'
      run: dotnet restore --locked-mode
    - name: Build HsMod
      if: steps.check-updates.outputs.has_updates == 'true'
      run: dotnet build --configuration Release --no-restore
    - name: Generate release tag
      if: steps.check-updates.outputs.has_updates == 'true'
      id: tag
      run: |
        Get-Content ./HsMod/PluginInfo.cs | Select-String -Pattern 'public const string PLUGIN_VERSION = "(.*?)"' | ForEach-Object { ($_ -match '"(.*?)"') | Out-Null }
        $version = $matches[1];
        echo "PLUGIN_VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        
    - name: Create Release
      if: steps.check-updates.outputs.has_updates == 'true'
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        CURRENT_TAG: ${{ steps.tag.outputs.PLUGIN_VERSION }}
      with:
        tag_name: ${{ steps.tag.outputs.PLUGIN_VERSION }}
        files: ./HsMod/Release/HsMod.dll
        prerelease: false
        make_latest: true
        generate_release_notes: true
      
